# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 926542bddb9ee8f01d3116546c0a10ac60e05882b2c7739f2f0fd6bce977e59daeb2643a131e80289dda2b42189f079f0d7bf89fbc472cc0229a783e3d17d02c

test:
  secret_key_base: b21686bf54fed997cc75761ed295f219513742e49c0023a09bef682eceafe8dba93c8bfab103d1dd57f762d389a5299d1c92b63a43754f71141c2e1b4901f1e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
